# Generated by Django 4.2.11 on 2026-05-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_etudiant_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='specialite',
            field=models.CharField(blank=True, max_length=150, verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='code_apogee',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code Apogée'),
        ),
    ]
