# Generated by Django 4.2.11 on 2026-05-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_alter_evaluation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
