# Generated by Django 4.2.11 on 2026-04-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='mention',
            field=models.CharField(blank=True, choices=[('TB', 'Très Bien'), ('B', 'Bien'), ('AB', 'Assez Bien'), ('P', 'Passable'), ('I', 'Insuffisant')], max_length=2, null=True, verbose_name='Mention'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='validation_jury',
            field=models.BooleanField(default=False, verbose_name='Validé par le jury'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='valide_St',
            field=models.BooleanField(default=False, verbose_name="Validé par l'étudiant"),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='rang',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rang dans la classe'),
        ),
    ]
