# Generated by Django 4.2.11 on 2026-04-29 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='enseignants',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='matieres',
        ),
        migrations.CreateModel(
            name='EnseignantMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_matieres', to='academics.classe', verbose_name='Classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_matieres', to='accounts.enseignant', verbose_name='Enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_matieres', to='academics.matiere', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Affectation Enseignant-Matière',
                'verbose_name_plural': 'Affectations Enseignant-Matière',
                'unique_together': {('enseignant', 'matiere', 'classe')},
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('motif', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motif')),
                ('justifiee', models.BooleanField(default=False, verbose_name='Justifiée')),
                ('duree_heures', models.FloatField(default=1.0, verbose_name='Durée (heures)')),
                ('enseignant_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='academics.enseignantmatiere', verbose_name='Cours (Enseignant-Matière)')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='accounts.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date'],
            },
        ),
    ]
