# Generated by Django 4.2.11 on 2026-05-04 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_enseignant_specialite_and_more'),
        ('academics', '0004_seance_absence_seance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('etudiant', 'seance', 'date')},
        ),
    ]
