# Generated by Django 4.2.11 on 2026-05-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_salle_seance_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='absences/justificatifs/', verbose_name='Justificatif'),
        ),
    ]
