# Generated by Django 4.2.11 on 2026-05-11 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_absence_created_at_absence_justificatif'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'année scolaire")),
                ('date_debut', models.DateField(verbose_name="Date de début de l'année")),
                ('date_fin', models.DateField(verbose_name="Date de fin de l'année")),
                ('est_active', models.BooleanField(default=False, verbose_name='Année active')),
            ],
            options={
                'verbose_name': 'Année Scolaire',
                'verbose_name_plural': 'Années Scolaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='periode',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='academics.anneescolaire', verbose_name='Année scolaire'),
        ),
    ]
