# Generated by Django 4.2.11 on 2026-05-11 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_anneescolaire_periode_annee_scolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='academics.anneescolaire', verbose_name='Année scolaire'),
        ),
    ]
