# Generated by Django 4.2.11 on 2026-05-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_anneescolaire_periode_annee_scolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='code',
            field=models.CharField(default='', max_length=5, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
