# Generated by Django 4.2.11 on 2026-04-29 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_recues', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='reponse',
            field=models.TextField(blank=True, null=True, verbose_name='Réponse'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('traitee', 'Traitée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
