# Generated by Django 4.2.11 on 2026-05-05 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_evaluation_enseignant'),
        ('communication', '0002_notification_from_user_reclamation_destinataire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='grades.note', verbose_name='Note concernée'),
        ),
    ]
