# Generated by Django 6.0.4 on 2026-05-09 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_reclamation_note'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('grades', '0005_alter_evaluation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_envoi',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='est_lu',
            new_name='is_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('absence', 'Absence'), ('note', 'Note'), ('reclamation', 'Réclamation'), ('system', 'Système')], default='system', max_length=20, verbose_name='Type de notification'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='grades.note', verbose_name='Note concernée'),
        ),
    ]
